### GENERAL SETTINGS ###

# Site settings
title: Gedanken
description: Hey there!
google_analytics:
theme:
baseurl: ""
url: "https://natashaw.github.io/gedanken/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

# Author Profile
email: natashawijoyo@gmail.com
