### GENERAL SETTINGS ###

# Site settings
title: Gedanken
description: Hey there!
google_analytics:
baseurl: ""
url: "https://natashaw.github.io/gedanken/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

# Author Profile
social:
  - title: linkedin
    url: http://www.linkedin.com/in/natashawijoyo
email: natashawijoyo@gmail.com
