### GENERAL SETTINGS ###

# Site settings
title: Gedanken
description: I am smiling.
google_analytics:
theme:
baseurl: "/gedanken"
url: "https://natashaw.github.io/gedanken"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more-->

# Author Profile
email: natashawijoyo@gmail.com
